apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: demo-con
    image: zxcvbnius/docker-demo
    ports:
    - containerPort: 3000
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-from-yaml
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-from-yaml
          key: password